services:
  db:
    image: 'postgres:14'
    ports:
      - "127.0.0.1:${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    environment:
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_DB_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_DB_PASSWORD
